apiVersion: v1
kind: Namespace
metadata:
  name: gomaxprocs-injector
  labels:
    gomaxprocs-injector/admission-webhooks: disabled

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gomaxprocs-injector
  namespace: gomaxprocs-injector
spec:
  dnsNames:
  - gomaxprocs-injector.gomaxprocs-injector.svc
  - gomaxprocs-injector.gomaxprocs-injector.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: gomaxprocs-injector-cert

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: gomaxprocs-injector
spec:
  selfSigned: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    gomaxprocs-injector/inject: disabled
  labels:
    app: gomaxprocs-injector
  name: gomaxprocs-injector
  namespace: gomaxprocs-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gomaxprocs-injector
  template:
    metadata:
      labels:
        app: gomaxprocs-injector
    spec:
      containers:
      - args:
        - --cert-file=/cert/tls.crt
        - --key-file=/cert/tls.key
        image: gjkim42/gomaxprocs-injector:${VERSION}
        name: gomaxprocs-injector
        volumeMounts:
        - mountPath: /cert
          name: cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: gomaxprocs-injector-cert

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: gomaxprocs-injector
  name: gomaxprocs-injector
  namespace: gomaxprocs-injector
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: gomaxprocs-injector
  type: NodePort

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: gomaxprocs-injector/gomaxprocs-injector
  name: gomaxprocs-injector
webhooks:
- name: gomaxprocs-injector.admisstion-controller.gjkim42
  namespaceSelector:
    matchExpressions:
    - key: gomaxprocs-injector/admission-webhooks
      operator: NotIn
      values:
      - disabled
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - cert-manager
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      name: gomaxprocs-injector
      namespace: gomaxprocs-injector
      path: /webhook
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  timeoutSeconds: 5
