name: Release

on:
  push:
    tags:
    - 'v*'

env:
  GO_VERSION: '1.20.2'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Release docker image
      run: |
        make image
        docker login -u gjkim42 -p "${DOCKER_PASSWORD}"
        make push RELEASE_LATEST=true
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PUSH_BOT_ACCESS_TOKEN }}
