name: Release

on:
  push:
    tags:
    - 'v*'

env:
  GO_VERSION: '1.19.2'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Release docker image
      run: |
        make image
        make image VERSION=latest
        docker login -u gjkim42 -p "${GJKIM42_DOCKER_PASSWORD}"
        make push
        make push VERSION=latest
      env:
        GJKIM42_DOCKER_PASSWORD: ${{ secrets.GJKIM42_DOCKER_PASSWORD }}

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Create a release note
      run: |
        go install k8s.io/release/cmd/release-notes@v0.12.0
        pre_tag=$(git describe --tags --abbrev=0 HEAD^)
        start=$(git log ${pre_tag}..HEAD --pretty=oneline | awk '{print $1}' | tail -n 1)
        end=$(git log ${pre_tag}..HEAD --pretty=oneline | awk '{print $1}' | head -n 1)
        release-notes \
          --dependencies=false \
          --output=${{ github.workspace }}/RELEASE_NOTES.md \
          --required-author= \
          --branch=main \
          --org=gjkim42 \
          --repo=gomaxprocs-injector \
          --start-sha=${start} \
          --end-sha=${end}
      env:
        GITHUB_TOKEN: "${{ secrets.FULL_REPO_TOKEN }}"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: false
        body_path: ${{ github.workspace }}/RELEASE_NOTES.md
